export interface BabyName {
  id: string;
  name: string;
  meaning: string;
  origin: string;
  gender: "boy" | "girl" | "unisex";
  popularity: number; // 1-100
  tags: string[];
}

export const origins = [
  "All",
  "Hindi",
  "Sanskrit",
  "Arabic",
  "English",
  "Hebrew",
  "Latin",
  "Greek",
  "Persian",
  "Turkish",
  "African",
  "Celtic",
  "Japanese",
  "Italian",
  "German",
  "French",
  "Irish",
  "Scottish",
  "Welsh",
  "Norse",
  "Russian",
  "Chinese",
  "Korean",
  "Indian",
  "Tamil",
  "Telugu",
  "Bengali",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Urdu",
] as const;

export const nameData: BabyName[] = [
  // Hindi / Sanskrit Names
  { id: "1", name: "Aarav", meaning: "Peaceful; wisdom", origin: "Sanskrit", gender: "boy", popularity: 95, tags: ["peace", "wisdom", "modern"] },
  { id: "2", name: "Vivaan", meaning: "Full of life", origin: "Sanskrit", gender: "boy", popularity: 92, tags: ["life", "energy", "modern"] },
  { id: "3", name: "Aditya", meaning: "Sun; belonging to Aditi", origin: "Sanskrit", gender: "boy", popularity: 88, tags: ["sun", "divine", "classic"] },
  { id: "4", name: "Arjun", meaning: "Bright, shining, white", origin: "Sanskrit", gender: "boy", popularity: 90, tags: ["warrior", "mahabharata", "classic"] },
  { id: "5", name: "Krishna", meaning: "Dark, black; the divine one", origin: "Sanskrit", gender: "boy", popularity: 85, tags: ["divine", "love", "classic"] },
  { id: "6", name: "Rohan", meaning: "Ascending; healing", origin: "Sanskrit", gender: "boy", popularity: 82, tags: ["growth", "healing", "modern"] },
  { id: "7", name: "Ayaan", meaning: "Gift of God", origin: "Arabic", gender: "boy", popularity: 93, tags: ["divine", "gift", "modern"] },
  { id: "8", name: "Reyansh", meaning: "Ray of light; part of a stream", origin: "Sanskrit", gender: "boy", popularity: 89, tags: ["light", "nature", "modern"] },
  { id: "9", name: "Vihaan", meaning: "Dawn; morning", origin: "Sanskrit", gender: "boy", popularity: 87, tags: ["morning", "new beginning", "modern"] },
  { id: "10", name: "Atharv", meaning: "Knowledge; the Vedas", origin: "Sanskrit", gender: "boy", popularity: 86, tags: ["knowledge", "vedas", "classic"] },
  { id: "11", name: "Sai", meaning: "Divine; saint", origin: "Sanskrit", gender: "boy", popularity: 78, tags: ["divine", "saint", "spiritual"] },
  { id: "12", name: "Ishaan", meaning: "The sun; Lord Shiva", origin: "Sanskrit", gender: "boy", popularity: 84, tags: ["sun", "shiva", "classic"] },
  { id: "13", name: "Ayaansh", meaning: "First ray of light", origin: "Sanskrit", gender: "boy", popularity: 80, tags: ["light", "morning", "modern"] },
  { id: "14", name: "Kabir", meaning: "Great; powerful", origin: "Arabic", gender: "boy", popularity: 81, tags: ["power", "saint", "classic"] },
  { id: "15", name: "Darsh", meaning: "Vision; sight", origin: "Sanskrit", gender: "boy", popularity: 75, tags: ["vision", "sight", "modern"] },
  { id: "16", name: "Samar", meaning: "Battle; evening conversation", origin: "Arabic", gender: "boy", popularity: 72, tags: ["warrior", "evening", "classic"] },
  { id: "17", name: "Zayan", meaning: "Beautiful; bright", origin: "Arabic", gender: "boy", popularity: 79, tags: ["beauty", "light", "modern"] },
  { id: "18", name: "Aarush", meaning: "First ray of the sun", origin: "Sanskrit", gender: "boy", popularity: 83, tags: ["sun", "morning", "modern"] },
  { id: "19", name: "Ansh", meaning: "Portion; part", origin: "Sanskrit", gender: "boy", popularity: 77, tags: ["part", "divine", "modern"] },
  { id: "20", name: "Laksh", meaning: "Aim; goal", origin: "Sanskrit", gender: "boy", popularity: 74, tags: ["goal", "prosperity", "classic"] },
  { id: "21", name: "Madhav", meaning: "Another name for Krishna", origin: "Sanskrit", gender: "boy", popularity: 70, tags: ["divine", "krishna", "classic"] },
  { id: "22", name: "Kiaan", meaning: "Grace of God", origin: "Sanskrit", gender: "boy", popularity: 73, tags: ["divine", "grace", "modern"] },
  { id: "23", name: "Shivansh", meaning: "Part of Lord Shiva", origin: "Sanskrit", gender: "boy", popularity: 76, tags: ["shiva", "divine", "modern"] },
  { id: "24", name: "Ranbir", meaning: "Brave warrior", origin: "Sanskrit", gender: "boy", popularity: 71, tags: ["brave", "warrior", "modern"] },
  { id: "25", name: "Yuvan", meaning: "Youthful; young", origin: "Sanskrit", gender: "boy", popularity: 68, tags: ["youth", "young", "modern"] },
  { id: "26", name: "Naksh", meaning: "Moon; feature", origin: "Sanskrit", gender: "boy", popularity: 69, tags: ["moon", "feature", "modern"] },
  { id: "27", name: "Aryan", meaning: "Noble; warrior", origin: "Sanskrit", gender: "boy", popularity: 85, tags: ["noble", "warrior", "classic"] },
  { id: "28", name: "Neil", meaning: "Champion; blue", origin: "Irish", gender: "boy", popularity: 80, tags: ["champion", "blue", "modern"] },
  { id: "29", name: "Vedant", meaning: "One who knows Vedas", origin: "Sanskrit", gender: "boy", popularity: 75, tags: ["knowledge", "vedas", "classic"] },
  { id: "30", name: "Pranav", meaning: "Sacred syllable Om", origin: "Sanskrit", gender: "boy", popularity: 78, tags: ["om", "sacred", "classic"] },
  { id: "31", name: "Shaurya", meaning: "Bravery; valor", origin: "Sanskrit", gender: "boy", popularity: 72, tags: ["bravery", "valor", "modern"] },
  { id: "32", name: "Rudra", meaning: "The howler; Lord Shiva", origin: "Sanskrit", gender: "boy", popularity: 70, tags: ["shiva", "storm", "classic"] },
  { id: "33", name: "Devansh", meaning: "Part of God", origin: "Sanskrit", gender: "boy", popularity: 74, tags: ["divine", "god", "modern"] },
  { id: "34", name: "Advik", meaning: "Unique", origin: "Sanskrit", gender: "boy", popularity: 79, tags: ["unique", "special", "modern"] },
  { id: "35", name: "Arnav", meaning: "Ocean; sea", origin: "Sanskrit", gender: "boy", popularity: 82, tags: ["ocean", "vast", "modern"] },
  { id: "36", name: "Parth", meaning: "Prince; Arjun", origin: "Sanskrit", gender: "boy", popularity: 76, tags: ["prince", "arjun", "classic"] },
  { id: "37", name: "Aryaman", meaning: "Noble-minded; friend", origin: "Sanskrit", gender: "boy", popularity: 65, tags: ["noble", "friend", "classic"] },
  { id: "38", name: "Indra", meaning: "Lord of the sky", origin: "Sanskrit", gender: "boy", popularity: 62, tags: ["sky", "rain", "classic"] },
  { id: "39", name: "Manav", meaning: "Human; mankind", origin: "Sanskrit", gender: "boy", popularity: 68, tags: ["human", "kind", "modern"] },
  { id: "40", name: "Om", meaning: "Sacred sound; universal", origin: "Sanskrit", gender: "boy", popularity: 60, tags: ["sacred", "universal", "spiritual"] },
  { id: "41", name: "Raghav", meaning: "Descendant of Raghu; Lord Rama", origin: "Sanskrit", gender: "boy", popularity: 71, tags: ["rama", "noble", "classic"] },
  { id: "42", name: "Tejas", meaning: "Brilliance; sharpness", origin: "Sanskrit", gender: "boy", popularity: 73, tags: ["brilliance", "sharp", "modern"] },
  { id: "43", name: "Yash", meaning: "Fame; glory", origin: "Sanskrit", gender: "boy", popularity: 77, tags: ["fame", "glory", "classic"] },
  { id: "44", name: "Zain", meaning: "Beauty; grace", origin: "Arabic", gender: "boy", popularity: 75, tags: ["beauty", "grace", "modern"] },
  { id: "45", name: "Farhan", meaning: "Happy; joyful", origin: "Arabic", gender: "boy", popularity: 66, tags: ["happy", "joy", "modern"] },
  { id: "46", name: "Ibrahim", meaning: "Father of many", origin: "Arabic", gender: "boy", popularity: 70, tags: ["father", "prophet", "classic"] },
  { id: "47", name: "Aahil", meaning: "Prince", origin: "Arabic", gender: "boy", popularity: 67, tags: ["prince", "royal", "modern"] },
  { id: "48", name: "Rehan", meaning: "Fragrant; scented", origin: "Arabic", gender: "boy", popularity: 64, tags: ["fragrance", "scent", "modern"] },
  { id: "49", name: "Taha", meaning: "Pure; mystic letters", origin: "Arabic", gender: "boy", popularity: 63, tags: ["pure", "mystic", "classic"] },
  { id: "50", name: "Sahil", meaning: "Guide; shore", origin: "Arabic", gender: "boy", popularity: 72, tags: ["guide", "shore", "modern"] },

  // Girl Names
  { id: "51", name: "Aadhya", meaning: "First power; beginning", origin: "Sanskrit", gender: "girl", popularity: 94, tags: ["power", "beginning", "modern"] },
  { id: "52", name: "Ananya", meaning: "Unique; unparalleled", origin: "Sanskrit", gender: "girl", popularity: 91, tags: ["unique", "special", "modern"] },
  { id: "53", name: "Diya", meaning: "Light; lamp", origin: "Sanskrit", gender: "girl", popularity: 89, tags: ["light", "lamp", "classic"] },
  { id: "54", name: "Saanvi", meaning: "Goddess Lakshmi", origin: "Sanskrit", gender: "girl", popularity: 93, tags: ["lakshmi", "goddess", "modern"] },
  { id: "55", name: "Aaradhya", meaning: "Worship; devotion", origin: "Sanskrit", gender: "girl", popularity: 88, tags: ["devotion", "worship", "modern"] },
  { id: "56", name: "Navya", meaning: "New; fresh; young", origin: "Sanskrit", gender: "girl", popularity: 85, tags: ["new", "fresh", "modern"] },
  { id: "57", name: "Myra", meaning: "Beloved; admirable", origin: "Latin", gender: "girl", popularity: 87, tags: ["beloved", "admirable", "modern"] },
  { id: "58", name: "Ira", meaning: "Watchful; earth goddess", origin: "Sanskrit", gender: "girl", popularity: 82, tags: ["earth", "goddess", "classic"] },
  { id: "59", name: "Sara", meaning: "Princess; noblewoman", origin: "Hebrew", gender: "girl", popularity: 84, tags: ["princess", "noble", "classic"] },
  { id: "60", name: "Aisha", meaning: "Alive; living", origin: "Arabic", gender: "girl", popularity: 86, tags: ["life", "living", "classic"] },
  { id: "61", name: "Zara", meaning: "Princess; blooming flower", origin: "Arabic", gender: "girl", popularity: 90, tags: ["princess", "flower", "modern"] },
  { id: "62", name: "Kiara", meaning: "Bright; clear; dark-haired", origin: "Italian", gender: "girl", popularity: 88, tags: ["bright", "clear", "modern"] },
  { id: "63", name: "Pari", meaning: "Fairy; angel", origin: "Persian", gender: "girl", popularity: 80, tags: ["fairy", "angel", "modern"] },
  { id: "64", name: "Amaira", meaning: "One who will be beautiful forever", origin: "Arabic", gender: "girl", popularity: 83, tags: ["beauty", "forever", "modern"] },
  { id: "65", name: "Anvi", meaning: "Goddess of forests", origin: "Sanskrit", gender: "girl", popularity: 81, tags: ["forest", "goddess", "modern"] },
  { id: "66", name: "Riya", meaning: "Singer; gem; grace", origin: "Sanskrit", gender: "girl", popularity: 79, tags: ["singer", "grace", "modern"] },
  { id: "67", name: "Meera", meaning: "Prosperous; famous", origin: "Sanskrit", gender: "girl", popularity: 78, tags: ["prosperity", "fame", "classic"] },
  { id: "68", name: "Siya", meaning: "Goddess Sita", origin: "Sanskrit", gender: "girl", popularity: 82, tags: ["sita", "goddess", "modern"] },
  { id: "69", name: "Aanya", meaning: "Inexhaustible; limitless", origin: "Sanskrit", gender: "girl", popularity: 84, tags: ["limitless", "grace", "modern"] },
  { id: "70", name: "Fatima", meaning: "One who abstains", origin: "Arabic", gender: "girl", popularity: 77, tags: ["pure", "prophet", "classic"] },
  { id: "71", name: "Inaya", meaning: "Concern; care", origin: "Arabic", gender: "girl", popularity: 80, tags: ["care", "concern", "modern"] },
  { id: "72", name: "Mia", meaning: "Mine; beloved", origin: "Italian", gender: "girl", popularity: 92, tags: ["beloved", "mine", "modern"] },
  { id: "73", name: "Aarohi", meaning: "A music tune; ascending", origin: "Sanskrit", gender: "girl", popularity: 76, tags: ["music", "tune", "modern"] },
  { id: "74", name: "Prisha", meaning: "Beloved; loving", origin: "Sanskrit", gender: "girl", popularity: 79, tags: ["beloved", "loving", "modern"] },
  { id: "75", name: "Kashvi", meaning: "Shining; luminous", origin: "Sanskrit", gender: "girl", popularity: 77, tags: ["shining", "luminous", "modern"] },
  { id: "76", name: "Anika", meaning: "Grace; brilliance", origin: "Sanskrit", gender: "girl", popularity: 81, tags: ["grace", "brilliance", "modern"] },
  { id: "77", name: "Sarah", meaning: "Princess; noblewoman", origin: "Hebrew", gender: "girl", popularity: 75, tags: ["princess", "noble", "classic"] },
  { id: "78", name: "Avni", meaning: "The earth", origin: "Sanskrit", gender: "girl", popularity: 74, tags: ["earth", "nature", "modern"] },
  { id: "79", name: "Tara", meaning: "Star; goddess", origin: "Sanskrit", gender: "girl", popularity: 73, tags: ["star", "goddess", "classic"] },
  { id: "80", name: "Rani", meaning: "Queen", origin: "Sanskrit", gender: "girl", popularity: 71, tags: ["queen", "royal", "classic"] },
  { id: "81", name: "Mira", meaning: "Ocean; admirable", origin: "Sanskrit", gender: "girl", popularity: 76, tags: ["ocean", "admirable", "classic"] },
  { id: "82", name: "Leela", meaning: "Divine play; amusement", origin: "Sanskrit", gender: "girl", popularity: 70, tags: ["play", "divine", "classic"] },
  { id: "83", name: "Noor", meaning: "Light; illumination", origin: "Arabic", gender: "girl", popularity: 78, tags: ["light", "illumination", "classic"] },
  { id: "84", name: "Zoya", meaning: "Alive; loving", origin: "Russian", gender: "girl", popularity: 75, tags: ["life", "loving", "modern"] },
  { id: "85", name: "Laila", meaning: "Night; dark beauty", origin: "Arabic", gender: "girl", popularity: 74, tags: ["night", "beauty", "classic"] },
  { id: "86", name: "Maryam", meaning: "Beloved; drop of the sea", origin: "Hebrew", gender: "girl", popularity: 73, tags: ["beloved", "pure", "classic"] },
  { id: "87", name: "Anaya", meaning: "Caring; without boundaries", origin: "Hebrew", gender: "girl", popularity: 80, tags: ["caring", "boundless", "modern"] },
  { id: "88", name: "Hazel", meaning: "The hazelnut tree", origin: "English", gender: "girl", popularity: 88, tags: ["tree", "nature", "modern"] },
  { id: "89", name: "Luna", meaning: "Moon", origin: "Latin", gender: "girl", popularity: 90, tags: ["moon", "celestial", "modern"] },
  { id: "90", name: "Stella", meaning: "Star", origin: "Latin", gender: "girl", popularity: 85, tags: ["star", "celestial", "modern"] },
  { id: "91", name: "Aurora", meaning: "Dawn", origin: "Latin", gender: "girl", popularity: 87, tags: ["dawn", "light", "modern"] },
  { id: "92", name: "Nova", meaning: "New", origin: "Latin", gender: "girl", popularity: 83, tags: ["new", "star", "modern"] },
  { id: "93", name: "Iris", meaning: "Rainbow; messenger", origin: "Greek", gender: "girl", popularity: 79, tags: ["rainbow", "messenger", "classic"] },
  { id: "94", name: "Freya", meaning: "Noble lady", origin: "Norse", gender: "girl", popularity: 81, tags: ["noble", "goddess", "modern"] },
  { id: "95", name: "Saoirse", meaning: "Freedom", origin: "Irish", gender: "girl", popularity: 68, tags: ["freedom", "liberty", "unique"] },
  { id: "96", name: "Isla", meaning: "Island", origin: "Scottish", gender: "girl", popularity: 89, tags: ["island", "river", "modern"] },
  { id: "97", name: "Aria", meaning: "Air; melody", origin: "Italian", gender: "girl", popularity: 91, tags: ["air", "melody", "modern"] },
  { id: "98", name: "Mila", meaning: "Gracious; dear", origin: "Slavic", gender: "girl", popularity: 90, tags: ["gracious", "dear", "modern"] },
  { id: "99", name: "Chloe", meaning: "Blooming; verdant", origin: "Greek", gender: "girl", popularity: 84, tags: ["blooming", "nature", "classic"] },
  { id: "100", name: "Elara", meaning: "Bright; shining", origin: "Greek", gender: "girl", popularity: 76, tags: ["bright", "moon", "modern"] },

  // Unisex Names
  { id: "101", name: "Jordan", meaning: "To flow down; descend", origin: "Hebrew", gender: "unisex", popularity: 82, tags: ["river", "flow", "classic"] },
  { id: "102", name: "Taylor", meaning: "Tailor; cutter of cloth", origin: "English", gender: "unisex", popularity: 78, tags: ["tailor", "craft", "classic"] },
  { id: "103", name: "Morgan", meaning: "Sea circle; bright sea", origin: "Welsh", gender: "unisex", popularity: 75, tags: ["sea", "circle", "classic"] },
  { id: "104", name: "Riley", meaning: "Valiant; rye clearing", origin: "Irish", gender: "unisex", popularity: 88, tags: ["valiant", "clearing", "modern"] },
  { id: "105", name: "Avery", meaning: "Ruler of the elves", origin: "English", gender: "unisex", popularity: 90, tags: ["elf", "ruler", "modern"] },
  { id: "106", name: "Quinn", meaning: "Wisdom; chief", origin: "Irish", gender: "unisex", popularity: 83, tags: ["wisdom", "chief", "modern"] },
  { id: "107", name: "Parker", meaning: "Park keeper", origin: "English", gender: "unisex", popularity: 80, tags: ["park", "keeper", "modern"] },
  { id: "108", name: "Sage", meaning: "Wise one; prophet", origin: "Latin", gender: "unisex", popularity: 77, tags: ["wise", "herb", "modern"] },
  { id: "109", name: "River", meaning: "Stream of water", origin: "English", gender: "unisex", popularity: 85, tags: ["water", "flow", "nature", "modern"] },
  { id: "110", name: "Skyler", meaning: "Scholar; sheltering", origin: "Dutch", gender: "unisex", popularity: 76, tags: ["scholar", "sky", "modern"] },
  { id: "111", name: "Dakota", meaning: "Friendly one; ally", origin: "Native American", gender: "unisex", popularity: 72, tags: ["friendly", "ally", "classic"] },
  { id: "112", name: "Reese", meaning: "Enthusiasm; ardent", origin: "Welsh", gender: "unisex", popularity: 79, tags: ["enthusiasm", "ardent", "modern"] },
  { id: "113", name: "Charlie", meaning: "Free man", origin: "English", gender: "unisex", popularity: 91, tags: ["free", "man", "classic"] },
  { id: "114", name: "Sasha", meaning: "Defender of mankind", origin: "Russian", gender: "unisex", popularity: 74, tags: ["defender", "mankind", "classic"] },
  { id: "115", name: "Eden", meaning: "Paradise; delight", origin: "Hebrew", gender: "unisex", popularity: 81, tags: ["paradise", "delight", "modern"] },
  { id: "116", name: "Amari", meaning: "Strength; builder", origin: "African", gender: "unisex", popularity: 73, tags: ["strength", "builder", "modern"] },
  { id: "117", name: "Sunny", meaning: "Bright; cheerful", origin: "English", gender: "unisex", popularity: 70, tags: ["sun", "cheerful", "modern"] },
  { id: "118", name: "Marley", meaning: "Pleasant wood", origin: "English", gender: "unisex", popularity: 75, tags: ["wood", "pleasant", "modern"] },
  { id: "119", name: "Kai", meaning: "Sea; warrior", origin: "Hawaiian", gender: "unisex", popularity: 84, tags: ["sea", "warrior", "modern"] },
  { id: "120", name: "Blake", meaning: "Dark; fair", origin: "English", gender: "unisex", popularity: 82, tags: ["dark", "fair", "classic"] },

  // More Boy Names
  { id: "121", name: "Noah", meaning: "Rest; comfort", origin: "Hebrew", gender: "boy", popularity: 96, tags: ["rest", "comfort", "classic"] },
  { id: "122", name: "Liam", meaning: "Strong-willed warrior", origin: "Irish", gender: "boy", popularity: 97, tags: ["strong", "warrior", "modern"] },
  { id: "123", name: "Oliver", meaning: "Olive tree", origin: "Latin", gender: "boy", popularity: 95, tags: ["olive", "tree", "peace", "modern"] },
  { id: "124", name: "Elijah", meaning: "Yahweh is God", origin: "Hebrew", gender: "boy", popularity: 94, tags: ["god", "divine", "classic"] },
  { id: "125", name: "James", meaning: "Supplanter", origin: "Hebrew", gender: "boy", popularity: 93, tags: ["supplanter", "classic", "royal"] },
  { id: "126", name: "William", meaning: "Resolute protector", origin: "German", gender: "boy", popularity: 92, tags: ["protector", "resolute", "royal"] },
  { id: "127", name: "Benjamin", meaning: "Son of the right hand", origin: "Hebrew", gender: "boy", popularity: 91, tags: ["son", "favored", "classic"] },
  { id: "128", name: "Lucas", meaning: "Bringer of light", origin: "Latin", gender: "boy", popularity: 90, tags: ["light", "bright", "modern"] },
  { id: "129", name: "Henry", meaning: "Ruler of the home", origin: "German", gender: "boy", popularity: 89, tags: ["ruler", "home", "classic"] },
  { id: "130", name: "Alexander", meaning: "Defender of mankind", origin: "Greek", gender: "boy", popularity: 88, tags: ["defender", "mankind", "classic"] },
  { id: "131", name: "Mason", meaning: "Stone worker", origin: "English", gender: "boy", popularity: 86, tags: ["stone", "worker", "modern"] },
  { id: "132", name: "Ethan", meaning: "Strong; firm", origin: "Hebrew", gender: "boy", popularity: 85, tags: ["strong", "firm", "classic"] },
  { id: "133", name: "Logan", meaning: "Little hollow", origin: "Scottish", gender: "boy", popularity: 84, tags: ["hollow", "small", "modern"] },
  { id: "134", name: "Daniel", meaning: "God is my judge", origin: "Hebrew", gender: "boy", popularity: 83, tags: ["god", "judge", "classic"] },
  { id: "135", name: "Sebastian", meaning: "Venerable; revered", origin: "Greek", gender: "boy", popularity: 82, tags: ["revered", "venerable", "modern"] },
  { id: "136", name: "Jack", meaning: "God is gracious", origin: "English", gender: "boy", popularity: 81, tags: ["gracious", "god", "classic"] },
  { id: "137", name: "Owen", meaning: "Young warrior; well-born", origin: "Welsh", gender: "boy", popularity: 80, tags: ["warrior", "noble", "modern"] },
  { id: "138", name: "Theodore", meaning: "Gift of God", origin: "Greek", gender: "boy", popularity: 79, tags: ["gift", "god", "classic"] },
  { id: "139", name: "Samuel", meaning: "Told by God", origin: "Hebrew", gender: "boy", popularity: 78, tags: ["god", "prophet", "classic"] },
  { id: "140", name: "Matthew", meaning: "Gift of God", origin: "Hebrew", gender: "boy", popularity: 77, tags: ["gift", "god", "classic"] },
  { id: "141", name: "Joseph", meaning: "He will add", origin: "Hebrew", gender: "boy", popularity: 76, tags: ["add", "increase", "classic"] },
  { id: "142", name: "Leo", meaning: "Lion", origin: "Latin", gender: "boy", popularity: 83, tags: ["lion", "brave", "modern"] },
  { id: "143", name: "Mateo", meaning: "Gift of God", origin: "Spanish", gender: "boy", popularity: 82, tags: ["gift", "god", "modern"] },
  { id: "144", name: "David", meaning: "Beloved", origin: "Hebrew", gender: "boy", popularity: 75, tags: ["beloved", "loved", "classic"] },
  { id: "145", name: "John", meaning: "God is gracious", origin: "Hebrew", gender: "boy", popularity: 74, tags: ["gracious", "god", "classic"] },
  { id: "146", name: "Wyatt", meaning: "Brave in war", origin: "English", gender: "boy", popularity: 79, tags: ["brave", "war", "modern"] },
  { id: "147", name: "Luke", meaning: "Light-giving", origin: "Greek", gender: "boy", popularity: 78, tags: ["light", "bright", "classic"] },
  { id: "148", name: "Julian", meaning: "Youthful; downy", origin: "Latin", gender: "boy", popularity: 77, tags: ["youth", "young", "modern"] },
  { id: "149", name: "Jayden", meaning: "Thankful God", origin: "Hebrew", gender: "boy", popularity: 76, tags: ["thankful", "god", "modern"] },
  { id: "150", name: "Grayson", meaning: "Son of the steward", origin: "English", gender: "boy", popularity: 75, tags: ["steward", "son", "modern"] },

  // More Girl Names
  { id: "151", name: "Olivia", meaning: "Olive tree", origin: "Latin", gender: "girl", popularity: 98, tags: ["olive", "tree", "peace", "modern"] },
  { id: "152", name: "Emma", meaning: "Whole; universal", origin: "German", gender: "girl", popularity: 97, tags: ["whole", "universal", "classic"] },
  { id: "153", name: "Charlotte", meaning: "Free woman", origin: "French", gender: "girl", popularity: 96, tags: ["free", "woman", "royal"] },
  { id: "154", name: "Amelia", meaning: "Work; industrious", origin: "German", gender: "girl", popularity: 95, tags: ["work", "industrious", "modern"] },
  { id: "155", name: "Sophia", meaning: "Wisdom", origin: "Greek", gender: "girl", popularity: 94, tags: ["wisdom", "knowledge", "classic"] },
  { id: "156", name: "Isabella", meaning: "Devoted to God", origin: "Hebrew", gender: "girl", popularity: 93, tags: ["devoted", "god", "classic"] },
  { id: "157", name: "Ava", meaning: "Bird; life", origin: "Latin", gender: "girl", popularity: 92, tags: ["bird", "life", "modern"] },
  { id: "158", name: "Mia", meaning: "Mine; beloved", origin: "Italian", gender: "girl", popularity: 91, tags: ["beloved", "mine", "modern"] },
  { id: "159", name: "Evelyn", meaning: "Desired; wished for", origin: "English", gender: "girl", popularity: 90, tags: ["desired", "wished", "classic"] },
  { id: "160", name: "Harper", meaning: "Harp player", origin: "English", gender: "girl", popularity: 89, tags: ["harp", "music", "modern"] },
  { id: "161", name: "Camila", meaning: "Young ceremonial attendant", origin: "Latin", gender: "girl", popularity: 88, tags: ["attendant", "young", "modern"] },
  { id: "162", name: "Gianna", meaning: "God is gracious", origin: "Italian", gender: "girl", popularity: 87, tags: ["gracious", "god", "modern"] },
  { id: "163", name: "Abigail", meaning: "Father's joy", origin: "Hebrew", gender: "girl", popularity: 86, tags: ["joy", "father", "classic"] },
  { id: "164", name: "Lily", meaning: "Pure; innocent; flower", origin: "English", gender: "girl", popularity: 85, tags: ["pure", "flower", "nature", "modern"] },
  { id: "165", name: "Ella", meaning: "Beautiful fairy woman", origin: "German", gender: "girl", popularity: 84, tags: ["fairy", "beautiful", "classic"] },
  { id: "166", name: "Elizabeth", meaning: "God is my oath", origin: "Hebrew", gender: "girl", popularity: 83, tags: ["god", "oath", "royal", "classic"] },
  { id: "167", name: "Sofia", meaning: "Wisdom", origin: "Greek", gender: "girl", popularity: 82, tags: ["wisdom", "knowledge", "classic"] },
  { id: "168", name: "Emily", meaning: "Rival; industrious", origin: "Latin", gender: "girl", popularity: 81, tags: ["rival", "industrious", "classic"] },
  { id: "169", name: "Avery", meaning: "Ruler of the elves", origin: "English", gender: "girl", popularity: 80, tags: ["elf", "ruler", "modern"] },
  { id: "170", name: "Scarlett", meaning: "Red", origin: "English", gender: "girl", popularity: 79, tags: ["red", "color", "modern"] },
  { id: "171", name: "Victoria", meaning: "Victory", origin: "Latin", gender: "girl", popularity: 78, tags: ["victory", "conquer", "royal", "classic"] },
  { id: "172", name: "Madison", meaning: "Son of Matthew", origin: "English", gender: "girl", popularity: 77, tags: ["gift", "god", "modern"] },
  { id: "173", name: "Luna", meaning: "Moon", origin: "Latin", gender: "girl", popularity: 82, tags: ["moon", "celestial", "modern"] },
  { id: "174", name: "Grace", meaning: "Charm; goodness; generosity", origin: "Latin", gender: "girl", popularity: 76, tags: ["grace", "charm", "classic"] },
  { id: "175", name: "Chloe", meaning: "Blooming; verdant", origin: "Greek", gender: "girl", popularity: 75, tags: ["blooming", "nature", "classic"] },
  { id: "176", name: "Penelope", meaning: "Weaver", origin: "Greek", gender: "girl", popularity: 74, tags: ["weaver", "craft", "classic"] },
  { id: "177", name: "Layla", meaning: "Night; dark beauty", origin: "Arabic", gender: "girl", popularity: 83, tags: ["night", "beauty", "modern"] },
  { id: "178", name: "Riley", meaning: "Valiant; courageous", origin: "Irish", gender: "girl", popularity: 73, tags: ["valiant", "brave", "modern"] },
  { id: "179", name: "Zoey", meaning: "Life", origin: "Greek", gender: "girl", popularity: 72, tags: ["life", "living", "modern"] },
  { id: "180", name: "Nora", meaning: "Light; honor", origin: "Irish", gender: "girl", popularity: 71, tags: ["light", "honor", "modern"] },
  { id: "181", name: "Eleanor", meaning: "Bright; shining one", origin: "Greek", gender: "girl", popularity: 76, tags: ["bright", "shining", "classic"] },
  { id: "182", name: "Hannah", meaning: "Favor; grace", origin: "Hebrew", gender: "girl", popularity: 70, tags: ["favor", "grace", "classic"] },
  { id: "183", name: "Addison", meaning: "Son of Adam", origin: "English", gender: "girl", popularity: 69, tags: ["adam", "son", "modern"] },
  { id: "184", name: "Aubrey", meaning: "Elf ruler", origin: "German", gender: "girl", popularity: 68, tags: ["elf", "ruler", "modern"] },
  { id: "185", name: "Ellie", meaning: "Shining light", origin: "Greek", gender: "girl", popularity: 73, tags: ["light", "shining", "modern"] },
  { id: "186", name: "Stella", meaning: "Star", origin: "Latin", gender: "girl", popularity: 75, tags: ["star", "celestial", "modern"] },
  { id: "187", name: "Natalie", meaning: "Birthday of the Lord", origin: "Latin", gender: "girl", popularity: 67, tags: ["birth", "christmas", "classic"] },
  { id: "188", name: "Zoe", meaning: "Life", origin: "Greek", gender: "girl", popularity: 72, tags: ["life", "living", "classic"] },
  { id: "189", name: "Leah", meaning: "Weary; delicate", origin: "Hebrew", gender: "girl", popularity: 66, tags: ["delicate", "gentle", "classic"] },
  { id: "190", name: "Hazel", meaning: "The hazelnut tree", origin: "English", gender: "girl", popularity: 78, tags: ["tree", "nature", "modern"] },
  { id: "191", name: "Violet", meaning: "Purple flower", origin: "Latin", gender: "girl", popularity: 77, tags: ["purple", "flower", "nature", "classic"] },
  { id: "192", name: "Aurora", meaning: "Dawn", origin: "Latin", gender: "girl", popularity: 80, tags: ["dawn", "light", "modern"] },
  { id: "193", name: "Savannah", meaning: "Open plain", origin: "Spanish", gender: "girl", popularity: 65, tags: ["plain", "nature", "modern"] },
  { id: "194", name: "Audrey", meaning: "Noble strength", origin: "English", gender: "girl", popularity: 69, tags: ["noble", "strength", "classic"] },
  { id: "195", name: "Brooklyn", meaning: "Broken land; water", origin: "English", gender: "girl", popularity: 64, tags: ["water", "land", "modern"] },
  { id: "196", name: "Bella", meaning: "Beautiful", origin: "Italian", gender: "girl", popularity: 71, tags: ["beautiful", "lovely", "modern"] },
  { id: "197", name: "Claire", meaning: "Clear; bright", origin: "French", gender: "girl", popularity: 68, tags: ["clear", "bright", "classic"] },
  { id: "198", name: "Skylar", meaning: "Scholar; eternal life", origin: "Dutch", gender: "girl", popularity: 67, tags: ["scholar", "sky", "modern"] },
  { id: "199", name: "Lucy", meaning: "Light", origin: "Latin", gender: "girl", popularity: 72, tags: ["light", "bright", "classic"] },
  { id: "200", name: "Paisley", meaning: "Church; pattern", origin: "Scottish", gender: "girl", popularity: 66, tags: ["church", "pattern", "modern"] },
];
